### ISSUE TITLE
Examples With Errors

### ISSUE THREAD

**Issue by Rodrhigo** [phpecc/phpecc#195]
Throws this error when I execute the tests of the files "creating_signature.php" and "ecdh_exchange.php":

<b>Fatal error</b>:  Uncaught Error: **Cannot use object of type** FG\ASN1\Universal\ObjectIdentifier **as array** in C:\xampp7\htdocs\vendor\mdanter\ecc\src\Serializer\PrivateKey\DerPrivateKeySerializer.php:106
Stack trace:
#0 C:\xampp7\htdocs\vendor\mdanter\ecc\src\Serializer\PrivateKey\PemPrivateKeySerializer.php(54): Mdanter\Ecc\Serializer\PrivateKey\DerPrivateKeySerializer-&gt;parse('0t\x02\x01\x01\x04 \xE6t\x8A\x81\x00\xC4\t\x00...')
#1 C:\xampp7\htdocs\vendor\mdanter\ecc\examples\creating_signature.php(22): Mdanter\Ecc\Serializer\PrivateKey\PemPrivateKeySerializer-&gt;parse('\nMHQCAQEEIOZ0io...')
#2 {main}
  thrown in <b>C:\xampp7\htdocs\vendor\mdanter\ecc\src\Serializer\PrivateKey\DerPrivateKeySerializer.php</b> on line <b>106</b>

**Comment by afk11** [comment]
What are you passing into PemPrivateKeySerializer? It seems to be missing the `BEGIN EC PRIVATE KEY` header that is expected for a PEM key. I would try this first.

Are you testing against keys produced by this library, or another implementation? The DerPrivateKeySerializer supports only one standard at the moment, so let me know what you're trying to test. 

If you want to check this out for yourself, play with this tool: https://lapo.it/asn1js/ or generate a sample key so I can take a look.

**Comment by afk11** [comment]
Closing due to inactivity. I think this was a case of passing the wrong input, but reopen if you have anything further to add.
